# Generated by Django 2.0.2 on 2018-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
