# Generated by Django 2.0.2 on 2018-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManagement', '0002_auto_20180305_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='system_version',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
