# Generated by Django 2.0.2 on 2018-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManagement', '0003_auto_20180305_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
