# Generated by Django 2.0.2 on 2018-03-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManagement', '0005_auto_20180305_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='total_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='used_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
