# Generated by Django 2.0.2 on 2018-03-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMManagement', '0006_auto_20180305_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
