# Generated by Django 2.0.2 on 2018-03-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMManagement', '0007_auto_20180306_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverinfo',
            old_name='used_memory',
            new_name='free_memory',
        ),
    ]
